server:
  port: 8090

spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/mercadopago
        registration:
          api-gateway-service:
            provider: keycloak-provider
            client-id: mspigateway-cliente
            client-secret: MvbhHV5OZIJsIFkRXIHbsR5Pr6nh2FfR
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
  cloud:
    gateway:
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
      default-filters: TokenRelay

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



